version: '3'

services:
  db1:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "ccp3bn_mca_projeto_integrado"
    ports:
      - "3307:3306"
    volumes:
      - db1_data:/var/lib/mysql

  db2:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "ccp3bn_mca_projeto_integrado"
    ports:
      - "3308:3306"
    volumes:
      - db2_data:/var/lib/mysql

volumes:
  db1_data:
  db2_data:
